"""create posts table

Revision ID: f3451c68b0b1
Revises: dbfe2cb0f0c0
Create Date: 2025-06-11 00:02:35.546286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3451c68b0b1'
down_revision = 'dbfe2cb0f0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(), nullable=False),
    sa.Column('post_content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    op.drop_table('posts')
    # ### end Alembic commands ###
